---
- name: Make sure user is on server and generate ssh key for it
  user: name={{ user_name }}
    generate_ssh_key=yes

#not required as authorized key is already set during create instance itself
- name: Add public keys for developers
  authorized_key: user={{ user_name }}
    key="{{ lookup('file', item) }}"
  with_fileglob:
    - /home/{{ user_name }}/.ssh/id_rsa.pub
# - name: Add public keys for developers
#   authorized_key:
#      user: '{{ user_name }}'
#      key: "{{ lookup('file', '/home/{{ user_name }}/.ssh/id_rsa.pub') }}"

